### ISSUE TITLE
img_read_error

### ISSUE THREAD

**Issue by zczs66** [HiXray-author/HiXray#4]
![Snipaste_2022-03-31_17-03-13](https://user-images.githubusercontent.com/57992038/161018998-7186bac7-cebc-48b2-9ee0-5a49a4a2659a.png)
请问你们当时实现时有出现数据集读取的错误吗，我已经删除了上一次出现错误的图片和标签，但再次运行还是会出现另外一批错误的图片

**Comment by lxsy-xcy** [comment]
我有同样的问题，请问您是怎么解决的呢？

**Comment by zczs66** [comment]
方便加个微信吗？zczs66





发自我的iPad


------------------ Original ------------------
From: linxusy ***@***.***&gt;
Date: Sat,May 14,2022 1:16 PM
To: HiXray-author/HiXray ***@***.***&gt;
Cc: zczs66 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [HiXray-author/HiXray] img_read_error (Issue #4)





 
我有同样的问题，请问您是怎么解决的呢？
